name: Discord Notification with Role and User Mentions

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify Discord with embed and mentions
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # Récupérer infos du commit
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          COMMIT_MSG_TITLE=$(git log -1 --pretty=format:'%s')
          COMMIT_MSG_BODY=$(git log -1 --pretty=format:'%b')

          # Mapping GitHub author → Discord user ID
          if [ "$AUTHOR_NAME" = "Le J" ]; then
            DISCORD_USER_ID="962313048926855188"  # ton ID Discord
          else
            DISCORD_USER_ID=""
          fi

          # ID du rôle Discord à mentionner (ex: @Développeurs)
          DISCORD_ROLE_ID="1366866195911020544"  # remplace par ton vrai ID de rôle

          # Mention utilisateur (inline)
          if [ -n "$DISCORD_USER_ID" ]; then
            AUTHOR_FIELD="**${AUTHOR_NAME}** (<@${DISCORD_USER_ID}>)"
          else
            AUTHOR_FIELD="**${AUTHOR_NAME}**"
          fi

          # Mention rôle (envoyé dans le champ `content`)
          MENTION_ROLE="<@&${DISCORD_ROLE_ID}>"

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "content": "'"${MENTION_ROLE}"'",
            "embeds": [{
              "title": "🚀 Nouveau commit poussé",
              "description": "Auteur : '"${AUTHOR_FIELD}"'\n**Dépôt :** '"${{ github.repository }}"'",
              "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
              "color": 5814783,
              "fields": [
                {
                  "name": "Message",
                  "value": "'"${COMMIT_MSG_TITLE}"'"
                },
                {
                  "name": "Description",
                  "value": "'"${COMMIT_MSG_BODY:-_Aucune description_}"'"
                },
                {
                  "name": "Branche",
                  "value": "${{ github.ref_name }}",
                  "inline": true
                },
                {
                  "name": "Lien",
                  "value": "[Voir le commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                  "inline": true
                }
              ],
              "footer": {
                "text": "GitHub Actions via Discord Webhook"
              },
              "timestamp": "'"$(date --iso-8601=seconds)"'"
            }]
          }' \
          $DISCORD_WEBHOOK
