name: Discord Notification with Embed

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify Discord with embed
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          COMMIT_MSG_TITLE=$(git log -1 --pretty=format:'%s')
          COMMIT_MSG_BODY=$(git log -1 --pretty=format:'%b')

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "🚀 Nouveau commit poussé",
              "description": "**Auteur : '"${AUTHOR_NAME}"'**\n**Dépôt :** '"${{ github.repository }}"'",
              "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
              "color": 5814783,
              "fields": [
                {
                  "name": "Message",
                  "value": "'"${COMMIT_MSG_TITLE}"'"
                },
                {
                  "name": "Description",
                  "value": "'"${COMMIT_MSG_BODY:-_Aucune description_}"'"
                },
                {
                  "name": "Branche",
                  "value": "${{ github.ref_name }}",
                  "inline": true
                },
                {
                  "name": "Lien",
                  "value": "[Voir le commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                  "inline": true
                }
              ],
              "footer": {
                "text": "GitHub Actions via Discord Webhook"
              },
              "timestamp": "'"$(date --iso-8601=seconds)"'"
            }]
          }' \
          $DISCORD_WEBHOOK
