name: Discord Notification with Embed and Mention in Author Name

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify Discord with embed and inline mention
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          AUTHOR_NAME=$(git log -1 --pretty=format:'%an')
          COMMIT_MSG_TITLE=$(git log -1 --pretty=format:'%s')
          COMMIT_MSG_BODY=$(git log -1 --pretty=format:'%b')

          # Associer les noms Git aux IDs Discord
          if [ "$AUTHOR_NAME" = "Le J" ]; then
            DISCORD_USER_ID="962313048926855188"  # Remplace par ton vrai ID Discord
          else
            DISCORD_USER_ID=""
          fi

          # Construire l'affichage de l'auteur avec mention
          if [ -n "$DISCORD_USER_ID" ]; then
            AUTHOR_FIELD="**${AUTHOR_NAME}** (<@${DISCORD_USER_ID}>)"
          else
            AUTHOR_FIELD="**${AUTHOR_NAME}**"
          fi

          curl -H "Content-Type: application/json" \
          -X POST \
          -d '{
            "embeds": [{
              "title": "🚀 Nouveau commit poussé",
              "description": "Auteur : '"${AUTHOR_FIELD}"'\n**Dépôt :** '"${{ github.repository }}"'",
              "url": "https://github.com/${{ github.repository }}/commit/${{ github.sha }}",
              "color": 5814783,
              "fields": [
                {
                  "name": "Message",
                  "value": "'"${COMMIT_MSG_TITLE}"'"
                },
                {
                  "name": "Description",
                  "value": "'"${COMMIT_MSG_BODY:-_Aucune description_}"'"
                },
                {
                  "name": "Branche",
                  "value": "${{ github.ref_name }}",
                  "inline": true
                },
                {
                  "name": "Lien",
                  "value": "[Voir le commit](https://github.com/${{ github.repository }}/commit/${{ github.sha }})",
                  "inline": true
                }
              ],
              "footer": {
                "text": "SNCF Transports PACA"
              },
              "timestamp": "'"$(date --iso-8601=seconds)"'"
            }]
          }' \
          $DISCORD_WEBHOOK
