name: Discord Notification per Commit

on:
  push:
    branches:
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Notify Discord for each commit
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          # ID du rôle Discord à mentionner (ex: @Développeurs)
          DISCORD_ROLE_ID="1366866195911020544"

          for row in $(jq -c '.commits[]' "$GITHUB_EVENT_PATH"); do
            # Extraire les données du commit
            COMMIT_SHA=$(echo "$row" | jq -r '.id')
            COMMIT_URL=$(echo "$row" | jq -r '.url')
            AUTHOR_NAME=$(echo "$row" | jq -r '.author.name')
            COMMIT_MSG_TITLE=$(echo "$row" | jq -r '.message' | head -n1)
            COMMIT_MSG_BODY=$(echo "$row" | jq -r '.message' | tail -n +2)

            # Associer noms Git aux IDs Discord
            if [ "$AUTHOR_NAME" = "Le J" ]; then
              DISCORD_USER_ID="962313048926855188"
            else
              DISCORD_USER_ID=""
            fi

            # Auteur affiché avec mention
            if [ -n "$DISCORD_USER_ID" ]; then
              AUTHOR_FIELD="**${AUTHOR_NAME}** (<@${DISCORD_USER_ID}>)"
            else
              AUTHOR_FIELD="**${AUTHOR_NAME}**"
            fi

            # Mention du rôle
            MENTION_ROLE="<@&${DISCORD_ROLE_ID}>"

            curl -H "Content-Type: application/json" \
              -X POST \
              -d '{
                "content": "'"${MENTION_ROLE}"'",
                "embeds": [{
                  "title": "🚀 Nouveau commit poussé",
                  "description": "Auteur : '"${AUTHOR_FIELD}"'\n**Dépôt :** '"${{ github.repository }}"'",
                  "url": "'"${COMMIT_URL}"'",
                  "color": 5814783,
                  "fields": [
                    {
                      "name": "Message",
                      "value": "'"${COMMIT_MSG_TITLE}"'"
                    },
                    {
                      "name": "Description",
                      "value": "'"${COMMIT_MSG_BODY:-_Aucune description_}"'"
                    },
                    {
                      "name": "Branche",
                      "value": "${{ github.ref_name }}",
                      "inline": true
                    },
                    {
                      "name": "Lien",
                      "value": "[Voir le commit]('"${COMMIT_URL}"')",
                      "inline": true
                    }
                  ],
                  "footer": {
                    "text": "GitHub Actions via Discord Webhook"
                  },
                  "timestamp": "'"$(date --iso-8601=seconds)"'"
                }]
              }' \
              $DISCORD_WEBHOOK
          done